### ISSUE TITLE
runtimeError: CUDA out of memory and program lock

### ISSUE THREAD

**Issue by ywdong** [marianna13/translate_dataset#3]
Any help! 
I have tune the batchsize 10 to 6, but i also got the runtime error, and the process will lock.
"""
Process Process-41:
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/group/20000/weidongyang/translate_dataset/translate_data_new.py", line 95, in translate_part
    device
  File "/group/20000/weidongyang/translate_dataset/translate_data_new.py", line 60, in process_data
    batched=True, batch_size=6)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2394, in map
    desc=desc,
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 551, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2768, in _map_single
    offset=offset,
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2644, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2336, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/group/20000/weidongyang/translate_dataset/translate_data_new.py", line 59, in <lambda>
    d = d.map(lambda example: {'ZH TEXT':translate(example['TEXT'], tokenizer, model, device)},
  File "/group/20000/weidongyang/translate_dataset/translate_data_new.py", line 47, in translate
    **encoded, forced_bos_token_id=tokenizer.get_lang_id("zh")).to(device)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/transformers/generation_utils.py", line 1325, in generate
    **model_kwargs,
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/transformers/generation_utils.py", line 2229, in beam_search
    model_kwargs["past"] = self._reorder_cache(model_kwargs["past"], beam_idx)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/transformers/models/m2m_100/modeling_m2m_100.py", line 1378, in _reorder_cache
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/transformers/models/m2m_100/modeling_m2m_100.py", line 1378, in <genexpr>
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 39.59 GiB total capacity; 483.86 MiB already allocated; 36.19 MiB free; 540.00 MiB reserved in total by PyTorch)
"""

**Comment by marianna13** [comment]
Please try with batch_size=1 and then try to increase it until you reach your GPU limit
